@startuml

state INITIAL
state BROWSING_CATALOG
state PRODUCT_DETAIL
state CART
state START_PURCHASE
state BROWSING_WALLET

[*] --> INITIAL
INITIAL --> BROWSING_CATALOG
CART --> START_PURCHASE

BROWSING_CATALOG --> PRODUCT_DETAIL
CART --> PRODUCT_DETAIL

INITIAL --> CART
BROWSING_CATALOG --> CART
PRODUCT_DETAIL --> CART
START_PURCHASE --> CART
BROWSING_WALLET --> CART

INITIAL --> BROWSING_WALLET
BROWSING_CATALOG --> BROWSING_WALLET
PRODUCT_DETAIL --> BROWSING_WALLET
CART --> BROWSING_WALLET
START_PURCHASE --> BROWSING_WALLET

INITIAL --> BROWSING_CATALOG
PRODUCT_DETAIL --> BROWSING_CATALOG
CART --> BROWSING_CATALOG
START_PURCHASE --> BROWSING_CATALOG
BROWSING_WALLET --> BROWSING_CATALOG

@enduml
